### ISSUE TITLE
Error running final node . command

### ISSUE THREAD

**Issue by kathekon** [filecoin-project/filecoin-client-tutorial#3]
Everything went smoothly until I got the following error when running the final "node ."  step:  (I should preface this by saying I'm a complete node novice so this may be user-error)
------------

curt@Curts-2019-MacBook-Pro-64gig filecoin-client-tutorial % node .
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '@babel/core'
Require stack:
- /Users/curt/filecoin_test/filecoin-client-tutorial/node_modules/@babel/register/lib/cache.js
- /Users/curt/filecoin_test/filecoin-client-tutorial/node_modules/@babel/register/lib/node.js
- /Users/curt/filecoin_test/filecoin-client-tutorial/node_modules/@babel/register/lib/index.js
- /Users/curt/filecoin_test/filecoin-client-tutorial/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/curt/filecoin_test/filecoin-client-tutorial/node_modules/@babel/register/lib/cache.js:19:37)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/curt/filecoin_test/filecoin-client-tutorial/node_modules/@babel/register/lib/cache.js',
    '/Users/curt/filecoin_test/filecoin-client-tutorial/node_modules/@babel/register/lib/node.js',
    '/Users/curt/filecoin_test/filecoin-client-tutorial/node_modules/@babel/register/lib/index.js',
    '/Users/curt/filecoin_test/filecoin-client-tutorial/index.js'
  ]
}

**Comment by EmanHerawy** [comment]
I have the same issue. when I have installed `@babel/core,` I got another dependency error  `Cannot find module 'babel-plugin-module-resolver' ` & when I've installed it I got another one  `Cannot find module 'next/babel' `. It seems like an infinite loop

**Comment by EmanHerawy** [comment]
@ #2 solves the issue

**Comment by jimmylee** [comment]
Awesome I'm glad, thanks :)
